[tool.poetry]
name = "geoapps-utils"
version = "0.1.0"
license = "MIT"
description = "Geoapps Utils"
authors = ["Mira Geoscience <support@mirageoscience.com>"]

[tool.poetry.scripts]

[tool.poetry.dependencies]
python = "^3.9, <3.11"

numpy = "~1.23.5"  # also in geoh5py
geoh5py = {version = "~0.8.0rc1", source = "pypi", allow-prereleases = true}

dash = {version = "~2.12", optional = true}
plotly = {version = "~5.13.1"}

pyqtwebengine = {version = "~5.15", optional = true}
pyside2 = {version = "~5.15", optional = true}

## indirect dependencies, forcing them here for installation through Conda not pip
Pillow = "~9.4.0"  # from geoh5py
h5py = "~3.8.0"  # from geoh5py

[tool.poetry.dev-dependencies]
pylint = "*"
pytest = "*"
pytest-cov = "*"
tomli = "*"

[tool.poetry.extras]
dash = [
    "dash",
    "pyqtwebengine",
    "pyside2",
]

[tool.conda-lock]
platforms = ['win-64', 'linux-64']
channels = ['conda-forge']

[tool.conda-lock.dependencies]
libblas = "*=*mkl"

[tool.isort]
# settings for compatibility between ``isort`` and ``black`` formatting
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.black]
# defaults are just fine

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
