[tool.poetry]
name = "geoapps_utils"
version = "0.1.0"
description = "Geoapps Utils"
authors = ["Mira Geoscience <support@mirageoscience.com>"]
packages = [
     { include = "geoapps_utils" }
]

[tool.poetry.scripts]


[tool.poetry.dependencies]
python = "^3.9, <3.11"

## dependencies for a minimal environment
numpy = "~1.23.5"
geoh5py = {version = "~0.8.0rc1", source = "pypi", allow-prereleases = true}

plotly = {version = "~5.13.1"}
pyqtwebengine = {version = "~5.15"}
pyside2 = {version = "~5.15"}
dash = {version = "~2.12"}

[tool.poetry.dev-dependencies]
pylint = "*"
pytest = "*"
pytest-cov = "*"
toml = "*"

[tool.conda-lock]
platforms = ['win-64', 'linux-64']
channels = ['conda-forge']

[tool.isort]
# settings for compatibility between ``isort`` and ``black`` formatting
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.black]
# defaults are just fine

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
