[tool.poetry]
name = "my-app"
version = "0.1.0-alpha.1"
description = "My application"
authors = ["Mira Geoscience <support@mirageoscience.com>"]
packages = [
     { include = "my_app" },
     { include = "my_app-assets" },
]

[tool.poetry.scripts]
my_app_hello = 'my_app.commands.hello'

[tool.poetry.dependencies]
python = "^3.9, <3.11"
h5py = "^3.2.1" # from geoh5py
numpy = "!=1.19.4, ^1.21.5, <1.23"  # scipy 1.7.3 requires numpy <1.23
pandas = "^1.3.5"
scipy = "^1.7.3"

## pip dependencies
geoh5py = { version = "0.6.0", source = "pypi" }
#geoh5py = { url = "https://github.com/MiraGeoscience/geoh5py/archive/refs/heads/main.tar.gz#sha256=None" }

[tool.poetry.dev-dependencies]
pylint = "*"
pytest = "*"
pytest-cov = "*"
toml = "*"

[tool.conda-lock]
platforms = ['win-64', 'linux-64']
channels = ['conda-forge']

[tool.isort]
# settings for compatibility between ``isort`` and ``black`` formatting
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.black]
# defaults are just fine

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
