schema_version: 1

context:
  name: geoapps-utils
  version: 0.5.0a1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: 4671fc21594f465fe3975ffba037a4a053e63d7038aca6fbcf5da0913532fcc2
  path: ../${{ name}}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10.0,<4.0.0
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=3.10.0,<3.11
    - numpy >=1.26.0,<1.27.0
    - pydantic >=2.5.2,<2.6.0
    - scipy >=1.14.0,<1.15.0
    - geoh5py >=0.11.0a1,<0.12.0a.dev
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0

tests:
  - python:
      imports:
        - geoapps_utils
  - files:
      source:
        - tests/
    requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Provides utility functions used by geoapps.
  description: |
    The geoapps-utils package provides utility functions used by
    (geoapps)<https://github.com/MiraGeoscience/geoapps>.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/geoapps-utils

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
