name: Publish Python Package

on:
    push:
        branches:
            - DEVOPS-425 # Temporary branch for testing
        tags:
            - '**'

jobs:
    call-workflow-publish-to-artifactory:
        name: Publish to Artifactory
        uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-publish_to_artifactory.yml@DEVOPS-425
        with:
            package_name: 'geoapps-utils'
            version_tag: '1.6.2'
        secrets:
            EXTRA_REPO_TOKEN: ${{ secrets.CONDA_REPO_ARTIFACTORY_REF_TOKEN }}
