name: Publish Python Package

on:
    release:
        types: [created]
    push:
        branches:
            - DEVOPS-425 # To test the workflow

jobs:
    call-workflow-publish-to-artifactory:
        name: Publish to Artifactory
        uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-publish_to_artifactory.yml@DEVOPS-425
        with:
            package_name: 'geoapps_utils'
            python_ver: '3.10'
            version_tag: 'v0.0.1'
            # version_tag: ${{ github.event.release.tag_name }}
        secrets:
            MIRA_CONDA_REPO_TOKEN: ${{ secrets.CONDA_REPO_ARTIFACTORY_REF_TOKEN }}
